language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ellqbPYkoCBt6F03UrA56Wv+ZaActYHe1xcmvbkEAZkiP+lu3sP/KlExPe0DU27BzV8Q82s+KPdXIUq4PTpNc0WzJiZi4ipixAf3iQwvYWi8SKnCgvK0CAQ/7Hh8O4b23tZctjRdHnMp3CFX2jf+FRz64VIhjX7I2fl6nPMy3U2EUrUOrqb7r6syqYGk6amzGlhSBeGHwsFlIGhuiHAW8BCORi7TNuMe+pmJyU7c0eJAmeoW1rzCwh54BPaQLwrI62nRHXlocZ8Ys3Vkc/y4fQ3Q1LcapIU3qT36Xkpn/QzCniwG9G4p3pQb7q6zFAcO5jzGAB++CSa7uZu4Fv/yLHJktwp71fZPeX/GjfbmD6UFgo1nrY2EKXSijfKBozbAiTHhxwzNczkVwP451Yb9S0aN5woq3/+Fr5MTu75GT7ZjeARWI3Hn9UWb8544Ccf+vq88AStuFZwZvlYoDr3VGOU6VztD5R/JUwOBDC5lt0weSivyZ5gtTlDs3EKBVwIEtYodoZ8VjdAEC/ECSNpE2fdpq26YUFyPTBofVyx6jjMOcjT1xWwWb4dAUTJDL8SQYgYKXnVdzi30H4SLBa2J0T1GXJOlS8PDfW4wzzkxpUDwwEh4RlEHwup21aT3JXiJoOmLOddS3/xHpF2SNWYyJXU5SxdeG2WUomny0iGnNU0=
  app: pacific-sands-86358
  on:
    repo: jolo217/second-capstone
