language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: b7Dxt+s4udq5wiYFL29dRZ30CcZSI8ZhylLD8J+YbYANBZtQ5IYBVVZzE1y94BOA63qWQzLA5kTBCeIfrWI3/Ln3R8QdCY1MXxZWdI8p/3vieHvDvoQNjbjbkEQS7WDn53Qgh4c86LzyXuoJMp3VZgUT7ODu4DiGQvv6GwjnwVLGllX2pvQBju/Wl140aeumhrSrn7XQwSpCMzLhNKlQP6rQR50HcjVQjqOXqLpwLcYuq2FB2jHvaQuA87xXLB8UtyewBCwFGuscxY9fkgOs1knDZ9w968ZKp979Vxk6E6i7Sp4K8v4LXq4rKh8dNcVH392ucjfjuqHt6sO+522tsJ8AuS33Ynm8iPYYZ7a1kwagmnBxaXUm0zq0jtvr6uK4wnoVJbJ3rfiTxoSToHtohEkbRVRJUQN0upZyj0dG8B6sxbBehFwHhzZbXx6nP162VfRmMN89FG+pWTmuKvaazlfcqxjaadVcGQq7Ckyhn4bbeGYdQI8AZ3jkp1s1HPjI7Em7fbkBJtq7p5asMpln34xtgsfxrnMVhhONvqbYNdJthmCOGugZiXoAEV3qJ8ESMH/g0rsGK19q4rMoXrDjmkbmNJDQ5M0AFqMhILikqVMQWm7Es/zRy+ZaRpYAo/QyZ0NciveqyP+/WNX48OSNYE++R4Tz+fCKJ6gwo28LCao=
  app: serene-waters-27170
  on:
    repo: jolo217/second-capstone