language: node_js
node_js: node
service:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: nsLP7ZOX9ib1zJUALcdb48Svm4aJhldZSSqoL/Gy4Jg9TT5Z3U7uhSjpHNKtf6PuVNwfExuSBYnG6YWjUrWv30efllify0ZEZr9CTlbVibscwj+Qo5ojYk+NXFtI0ACiCNmKhIzzGBttPH/WO60GPXn54HF0RabKXOB+O+F8lnXT4NQH5tmIXOEgAuuijdwikrOKEqNH3PGtY5GtpUNU/Z62WxhtH33yZPP1dknmxrLWxFV1/IMgAD2TzE7l1zHnfGixdm74oYkxjiPCrcg8h7Pypf+uR0KJi9RWmZSRQBC8pv6rZaSGK7s1q/YyIuIhX/UWqBtIvi/ADH9lu3fS6a1w8uK9BH7T5e/POUKfip74IapPZxDd6lT2rQuokdXb08plV5HDWd4V23DI1CIw+YYmoHmOpelasJcwenSPW9ErhJn1kyS+PcVFGirMemLLayaMRIE7TTQb9gyU6uRspfGYackdS6mVk2AxgHvLGyrt4hojDoTu8u4gVOrRPkuCNQqj8FRdXBW50is+OeIC6N+XCrKWeTGE5kUaFbRp9hDEYDRCumvUPBAHaK8jfk7Rv4MiYjeXgv1pbasdwP2qlIMewPtFqdRB2xejrL5RdoVomGTapdwaxGZtPO6tsxzk5JB5NoUyYe2k/1XAC5DoNTHhIoZA9A3d5L8u2zg4ySA=
  app: pacific-sands-86358
  on:
    repo: jolo217/second-capstone
