language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DuueUZUqRqLP7zUSVO6VApal1IpvBm2xZhtmaxByI+bIxxXHIlO1VxWRlH+rSzs4u9XlGK+9ziML1JE/SmoMTlsTTaCZkStLUfRy0hBYIVcu763J9tN+sgyVIXB25MP8UToKtIM8hmuLGttafxGMiKzDgWmQUIEN/cZlWVqDn5xpToaLs2BSwW37f04aPyl0ySNQAmI4GFXIKv2clWkd6UV2Q1wnMDFgABCTyekRqFHQdC+dzRTIqdA6ShsJtFx8qeUXJ5gxnrBqsqaASJ7s5k28nUvVgTgZDcCu7tu+BWObFPNQR/1lPukQRjqBzSLpsYSaPF56sh3r4GwvSpPm5l4Vfm1jLQHf//6c79hCBRkcgq6nWfAGi2HuYdpOLX1joqBq1NS93rF6ClNdG9jeAY9So6YTstiSk7QaZYaHnNaY5w2TcNtF3SWwkANORRCV3lJ3fz927YlGANoqATvWrXSMc4uKW7U8w/JrWpom4ilUdktxQBTkv6YWcot89jVsToG4hpsA5CZwtUiounWpoLcNsWvfdPDf9UFzl9N5CgGv4nY/9aE26mLN1shkVBkfOCn3wF/HA60bIn2G9nZL7T/NiQz/1nVPWpr8qYgU7Yl7Q0d669pVY8Tb+C0GM0ZIFCHt6gqikGmcgEeVs1UKa6xJ8RcIuOwLm1ow1fHGovk=
  app: serene-waters-27170
  on:
    repo: jolo217/second-capstone
